---
-  name: installing spurt commerce
   become: yes
   hosts: all
   vars:
     - node_source: https://deb.nodesource.com/setup_14.x
     - root_user: root
     - apache_version: apache2
     
       
  
   tasks:
     - name: installing nodesource
       ansible.builtin.uri:
         url: "{{ node_source }}"
       become: yes
       become_user: "{{ root_user }}"
     - name: installing nodejs
       apt:
         name: nodejs
     - name: installing build-essential
       apt:
         name: 
           - build-essential
           - npm
     - name: installing nodejs libraries
       community.general.npm:
         name: "{{ item }}"
         global: yes
       loop: 
         - forever  
         - apidoc  
     - name: installing apache2
       apt :
         name: "{{ apache_version }}"
         update_cache: yes
     - name: Enable the Apache2 modules
       apache2_module:
         name: proxy
         state: present
         
     - name: restarting apache2
       ansible.builtin.systemd:
         name: apache2
         daemon_reload: yes
         state: restarted
